version: '3.7'

services:
  identifier:
    image: semtech/mu-identifier:1.8.1
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0-beta.2
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./data/db:/data
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
  cache:
    image: semtech/mu-cache:2.0.0
    links:
      - resource:backend
  resource:
    image: semtech/mu-cl-resources:1.19.0
    volumes:
      - ./config/resources:/config
